{{- if and .Values.contour.serviceAccount.create .Values.contour.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.contour.certgen.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourCertGenServiceAccountName" . }}
  labels: {{- include "contour.labels" . | nindent 4 }}
{{- end }}
{{- if and .Values.envoy.serviceAccount.create .Values.envoy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy.envoyServiceAccountName" . }}
  labels: {{- include "envoy.labels" . | nindent 4 }}
{{- end }}